### ISSUE TITLE
Improve tsconfig

### ISSUE THREAD

**Issue by marcomuser** [remix-run/react-router-templates#14]
Some of the options could be modernized or are superfluous:
1. `"forceConsistentCasingInFileNames"` is `true` by default. You don't need to set it explicitly.
2. In the react-router docs [it's recommended](https://reactrouter.com/how-to/route-module-type-safety#4-type-only-auto-imports-optional) to configure VSCode to add type modifiers to imports automatically. However, this can be enabled automatically by setting `"verbatimModuleSyntax": true` in tsconfig.json. This will enforce those type imports and IDE's will pick that up and add them for you automatically when importing via autocompletion.
3. If we set verbatimModuleSyntax, `"isolatedModules": true` is implied by default as well and can be removed from the tsconfig
4. I would also suggest to look into alternatives for project references which are hard to understand and usually unnecessary if one doesn't use tsc for building the project. Jared Palmer has our back here: [You might not need TypeScript project references](https://turbo.build/blog/you-might-not-need-typescript-project-references).
5. I would switch to setting `"module": "nodenext"` instead of `"module": "esnext"` and `"moduleResolution": "bundler"`. This newer mode enforces file extensions for relative imports. It's thus much closer to the ESM standard. In principle, this mode implies ESM + node_modules. For users, this generally means no change of habits for new projects, as the IDE (e.g. VSCode) picks up this configuration immediately and handles it correctly for import autocompletions. For context see also: https://github.com/remix-run/react-router/issues/12424#issuecomment-2512821234
6. In combination with nodenext I think it make sense to also set `"allowImportingTsExtensions": true`. Since react-router projects are built by Vite and not tsc, we can relax this ts specific import rule (aka "imports should be written as required by the target runtime") a tiny bit.
7. Instead of tsconfig paths (currently the default template has `"~/*": ["./app/*"]`), use the standardized Node.js [subpath imports](https://nodejs.org/api/packages.html#subpath-imports). If you configure your path imports in your package.json instead of your tsconfig.json, your whole toolchain will pick it up automatically! TypeScript knows how to resolve those imports, VSCode knows, Vite knows, Node.js knows... TypeScript paths are "intended to describe mappings that the build tool or runtime already performs, not to tell the build tool or runtime how to resolve modules." See: [ts-node docs](https://typestrong.org/ts-node/docs/paths#why-is-this-not-built-in-to-ts-node). So instead of misusing a ts feature which is not meant for that we can use a package.json feature which was created exactly for this use-case!

**Comment by brookslybrand** [comment]
Implemented in #21 

Thanks @marcomuser for these suggestions! I'm going to go ahead and close this issue
