### ISSUE TITLE
Shouldn't React Router 7 Provide Better Support for JavaScript Users?

### ISSUE THREAD

**Issue by wanGiB** [remix-run/react-router-templates#7]
Why do both the documentation and templates for React Router 7 seem to enforce the use of TypeScript?

Considering that React Router 7 appears to be inspired by legacy SPAs, many of which are built with plain JavaScript, this approach seems inconsistent. A significant number of legacy React SPAs still use JavaScript rather than TypeScript.

Shouldn't the React Router CLI and documentation offer clear options for choosing between JavaScript and Typescript, rather than defaulting to or heavily emphasizing only TypeScript?

**Comment by brookslybrand** [comment]
I won't speak on docs/CLI here, but I do agree that we should have a JS only template

I started one here in #11, not sure what I'm doing wrong at the moment for dev/build not to work

**Comment by chinfeng** [comment]
Agree! Not only js only template, I also need SPA template!

**Comment by marcomuser** [comment]
Barebones SPA templates for JS and for TS would be pretty nice. For educational purposes it's a bit overwhelming to have someone bootstrap a react-router app and be greeted with Tailwind configs, Docker for different runtimes, complex tsconfig setups for SSR etc.

**Comment by brandonxiang** [comment]
@chinfeng here is a simplist SPA template https://github.com/brandonxiang/vite-antd-starter

**Comment by marcomuser** [comment]
Your template does not follow the new React router framework conventions. I think it would be super useful to have an official template starter that bootstraps a simple SPA (in js or ts) in “framework mode” that is easily upgradeable to SSR if desired. Basically a template that bootstraps what is described in this guide: https://reactrouter.com/how-to/spa#single-page-app-spa. This way a new user doesn't have to deal with servers and all that stuff right away, but is already guided on the right path if the use case warrants it (..and I have to say there are more cases than the twitter bubble would have you believe where a SPA is preferred). Isn't that exactly one of the fantastic things about react-router's new version?

**Comment by brookslybrand** [comment]
Yep, we definitely want to have a SPA template. If someone just wants to copy the basic template and adjust it to be SPA, feel free to tag me on the PR. I'll get to it eventually, but if someone else beats me that's even better
