### ISSUE TITLE
Cloudflare D1 template does not serve static assets

### ISSUE THREAD

**Issue by taobojlen** [remix-run/react-router-templates#8]
The Cloudflare D1 template (and likely the Cloudflare template too!) does not serve any static assets when you build & deploy it.

To reproduce:

- Clone the template and `cd` into the folder
- Make the change described in https://github.com/remix-run/react-router-templates/issues/2 to get builds to work
- `npm install && npm run build && npm start`
- Visit `http://localhost:8787`. In your terminal logs you'll see things like

```
[wrangler:inf] Ready on http://localhost:8787
[wrangler:inf] GET / 200 OK (44ms)
✘ [ERROR] Error: No route matches URL "/assets/entry.client-65eIbm27.js"
[wrangler:inf] GET /assets/entry.client-65eIbm27.js 404 Not Found (8ms)
[wrangler:inf] GET /assets/chunk-7R3XDUXW-BhZqBB9S.js 404 Not Found (12ms)
[wrangler:inf] GET /assets/root-Bn4Ngxxb.css 404 Not Found (12ms)
[wrangler:inf] GET /assets/with-props-CjRNnwNJ.js 404 Not Found (15ms)
[wrangler:inf] GET /assets/root-Dj4aptwQ.js 404 Not Found (15ms)
[wrangler:inf] GET /assets/home-BgHCt-4A.js 404 Not Found (15ms)
[wrangler:inf] GET /assets/logo-dark-pX2395Y0.svg 404 Not Found (3ms)
[wrangler:inf] GET /assets/logo-light-CVbx2LBR.svg 404 Not Found (3ms)
```

If you run things in dev with `npm run dev`, static assets are served correctly, but it breaks when you try to actually deploy it.

**Comment by foxlau** [comment]
The reason is that the line # assets = { directory = "./build/client/" } in wrangler.toml is commented out.
